FROM --platform=$TARGETPLATFORM alpine

LABEL maintainer "Jrohy <euvkzx@gmail.com>"

ARG TARGETOS

ARG TARGETARCH

RUN apk add --no-cache tzdata libc6-compat

COPY result/webssh_$TARGETOS_$TARGETARCH /webssh

ENTRYPOINT ["/webssh"]
